### ISSUE TITLE
Multiple instances on same page

### ISSUE THREAD

**Issue by bazalt** [fabianwennink/IconCaptcha-Plugin-Front-End#6]
Hi there,
Is there a recommended way to make IconCaptcha work when integrated on multiple forms, on a same page ?

In my case, IconCaptcha renders well on the first form. But for the followings, I got this error in console : 
`icon-captcha.min.js?ver=3.1.1:2 IconCaptcha has already been initialized.`

This error is triggered through `IconCaptcha.init()` -> `_initShared` :
https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/blob/0cb6a19cf74047e69cefb5fd44451eeba0c01f16/src/js/icon-captcha.js#L139-L145

I precise that in my case, `IconCaptcha.init()` is called with different and unique selectors that don't overlapse, as well as distinct options.

Thanks,
Cyril.

**Comment by fabianwennink** [comment]
Hi @bazalt! 

At the moment, it is not possible to initialize IconCaptcha with `IconCaptcha.init()` more than once on the same page. You can still have more than 1 captcha on a single page by using the same selector for each captcha, but you can't have a different configuration for each captcha.

It's been a while since v3.0.0 was released and this change was implemented (when the transition away from jQuery was made), so I'm not really sure why this limitation was implemented. I'll see if I can easily implement a way to make it possible to use `init` more than once on the same page, somewhere in the upcoming days.

**Comment by fabianwennink** [comment]
I've tried to alter to code to allow for `IconCaptcha.init()` to be used more than once with different selectors and options, however with how the code currently works, I can't implement this without breaking backwards compatibility. I've put this enhancement on hold for now, and will implement this in the upcoming major version (v4).

**Comment by fabianwennink** [comment]
Hi @bazalt! I have an update regarding this issue, see my reply in this discussion: https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/discussions/10#discussioncomment-6295949

**Comment by fabianwennink** [comment]
Hi @bazalt. As I said in the discussion (https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/discussions/10#discussioncomment-6295949), I've now merged the specific commit into the 3.x branch. Could you perhaps try out this change and let me know if this works for your use case?

**Comment by fabianwennink** [comment]
Hi @bazalt! The latest release [3.1.2](https://github.com/fabianwennink/IconCaptcha-Plugin-Front-End/releases/tag/3.1.2) fixed this issue. You can now initialize IconCaptcha more than once with `IconCaptcha.init`.
